[package]
name = "offline-phragmen"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
url = "2.1.0"
futures = "0.1.29"
hyper = "0.12"
separator = "0.4.1"
codec = { package = "parity-scale-codec", version = "1.0.6", default-features = false, features = ["derive"] }
jsonrpc-core-client = { version = "14.0.3", features = ["http", "ws", "tls"] }
clap = "2.33.0"

polkadot-primitives = { git = "https://github.com/paritytech/polkadot", rev = "f23ce3e9184153f923139f33d1b05f92c62e3a7b" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-master" }
sp-phragmen = { git = "https://github.com/paritytech/substrate", branch = "polkadot-master" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-master", features = ["std"] }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-master" }
support = { package = "frame-support", git = "https://github.com/paritytech/substrate", branch = "polkadot-master" }
staking = { package = "pallet-staking", git = "https://github.com/paritytech/substrate", branch = "polkadot-master" }
