[package]
name = "offline-phragmen"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
url = "2.1.0"
futures = "0.1.29"
hyper = "0.12"
separator = "0.4.1"
codec = { package = "parity-scale-codec", version = "1.0.6", default-features = false, features = ["derive"] }
jsonrpc-core-client = { path = "/Users/kianenigma/Desktop/Parity/jsonrpc/core-client", features = ["http", "ws", "tls"] }
serde = { version = "1.0.102", features = ["derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
clap = "2.33.0"

polkadot-primitives = { path = "../polkadot/primitives" }
substrate-rpc-api = { path = "../substrate/core/rpc/api" }
substrate-phragmen = { path = "../substrate/core/phragmen" }
substrate-primitives = { path = "../substrate/core/primitives" }
sr-primitives = { path = "../substrate/core/sr-primitives" }
srml-support = { path = "../substrate/srml/support" }
srml-staking = { path = "../substrate/srml/staking" }
