[package]
name = "offline-phragmen"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
url = "2.1.0"
futures = "0.1.29"
hyper = "0.12"
separator = "0.4.1"
codec = { package = "parity-scale-codec", version = "1.0.6", default-features = false, features = ["derive"] }
jsonrpc-core-client = { version = "13.2.0", features = ["http", "ws", "tls"] }

polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "v0.6" }
substrate-rpc-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-master" }
substrate-phragmen = { git = "https://github.com/paritytech/substrate", branch = "polkadot-master" }
substrate-primitives = { git = "https://github.com/paritytech/substrate", branch = "polkadot-master" }
sr-primitives = { git = "https://github.com/paritytech/substrate", branch = "polkadot-master" }
support = { package = "srml-support", git = "https://github.com/paritytech/substrate", branch = "polkadot-master" }
staking = { package = "srml-staking", git = "https://github.com/paritytech/substrate", branch = "polkadot-master" }
