[package]
name = "offline-phragmen"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
url = "2.1.0"
futures = "0.1.29"
hyper = "0.12"
separator = "0.4.1"
codec = { package = "parity-scale-codec", version = "1.0.6", default-features = false, features = ["derive"] }
jsonrpc-core-client = { version = "14.0.3", features = ["http", "ws", "tls"] }
serde = { version = "1.0.102", features = ["derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
clap = "2.33.0"

polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "master"}
substrate-rpc-api = { git = "https://github.com/paritytech/substrate", branch = "kiz-serde-phragmen" }
substrate-phragmen = { git = "https://github.com/paritytech/substrate", branch = "kiz-serde-phragmen" }
substrate-primitives = { git = "https://github.com/paritytech/substrate", branch = "kiz-serde-phragmen"}
sr-primitives = { git = "https://github.com/paritytech/substrate", branch = "kiz-serde-phragmen" }
support = { package = "srml-support", git = "https://github.com/paritytech/substrate", branch = "kiz-serde-phragmen" }
staking = { package = "srml-staking", git = "https://github.com/paritytech/substrate", branch = "kiz-serde-phragmen" }
